### ISSUE TITLE
Add python environnement handling

### ISSUE THREAD

**Issue by pyb01-git** [edissyum/opencaptureformaarch#92]
I had an issue when both OC4Invoice and OC4Maarch were installed on the same server. 
There were a conflict in python packages.
The usage of a python environment would prevent most conflicts.
If possible using the directory /opt/maarch instead of the user's home (ex /home/edissyum/python-venv/opencapture) .
So the installation is not linked to the current user.

**Comment by nathan30** [comment]
Available in the next release
